name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions
on:
  workflow_dispatch:

jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
    # Bij een run geef je aan dat het een linux commando is. 
      - run: echo "HI dit is een test" 
      - name: Ander Test
        run: echo "Ander test"
