name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions
on:
# Handmatige runs
  workflow_dispatch:

jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
    # Bij een run geef je aan dat het een linux commando is. 
      - run: echo "HI dit is een test" 
    # Geef een duidelijke naam bij de test
      - name: Ander Test
        run: echo "Ander test"
        
  Input-Output-parallel:
    runs-on: ubuntu-latest
    # Output toevoegen zodat het in andere jobs gebruikt kan worden
    outputs:
      OUTPUTVOORBEELD: ${{ steps.output_step.outputs.OUTPUTVOORBEELD }}
    steps:
    #stap met een output
      - name: Set output variable
    #id is nodig bij een output
        id: output_step
        run: |
          echo "OUTPUTVOORBEELD=Hallo, dit is een output!" >> $GITHUB_OUTPUT
#nieuwe stap waar gebruik gemaakt wordt van output van vorige stap
      - name: Print output variable
        run:  | 
          echo "De output is: ${{ steps.output_step.outputs.OUTPUTVOORBEELD }}"

  Ander-Job-Input:
    runs-on: ubuntu-latest
    # Runt pas nadat vorige job klaar is
    needs: [Input-Output-parallel]
    steps:
    # Verwijst naar ander job step, hier zal niets uit moeten komen 
      - name: Print output variable
        run:  | 
          echo "De output is: ${{ needs.Input-Output-parallel.outputs.OUTPUTVOORBEELD }}"
